<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblBidangusaha', 'doctrine');

/**
 * BaseTblBidangusaha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ckode_usaha
 * @property string $cketerangan
 * @property string $cdetail
 * @property string $ctransfer
 * @property Doctrine_Collection $TblCustomer
 * 
 * @method string              getCkodeUsaha()  Returns the current record's "ckode_usaha" value
 * @method string              getCketerangan() Returns the current record's "cketerangan" value
 * @method string              getCdetail()     Returns the current record's "cdetail" value
 * @method string              getCtransfer()   Returns the current record's "ctransfer" value
 * @method Doctrine_Collection getTblCustomer() Returns the current record's "TblCustomer" collection
 * @method TblBidangusaha      setCkodeUsaha()  Sets the current record's "ckode_usaha" value
 * @method TblBidangusaha      setCketerangan() Sets the current record's "cketerangan" value
 * @method TblBidangusaha      setCdetail()     Sets the current record's "cdetail" value
 * @method TblBidangusaha      setCtransfer()   Sets the current record's "ctransfer" value
 * @method TblBidangusaha      setTblCustomer() Sets the current record's "TblCustomer" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblBidangusaha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_bidangusaha');
        $this->hasColumn('ckode_usaha', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('cketerangan', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cdetail', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'F',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ctransfer', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'N',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblCustomer', array(
             'local' => 'ckode_usaha',
             'foreign' => 'ckode_usaha'));
    }
}