<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblSales', 'doctrine');

/**
 * BaseTblSales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ckode_sales
 * @property string $ckode_loket
 * @property string $cnama
 * @property string $ctransfer
 * @property string $calamat
 * @property string $cstatus
 * @property TblLoket $TblLoket
 * @property Doctrine_Collection $TblCustomer
 * 
 * @method string              getCkodeSales()  Returns the current record's "ckode_sales" value
 * @method string              getCkodeLoket()  Returns the current record's "ckode_loket" value
 * @method string              getCnama()       Returns the current record's "cnama" value
 * @method string              getCtransfer()   Returns the current record's "ctransfer" value
 * @method string              getCalamat()     Returns the current record's "calamat" value
 * @method string              getCstatus()     Returns the current record's "cstatus" value
 * @method TblLoket            getTblLoket()    Returns the current record's "TblLoket" value
 * @method Doctrine_Collection getTblCustomer() Returns the current record's "TblCustomer" collection
 * @method TblSales            setCkodeSales()  Sets the current record's "ckode_sales" value
 * @method TblSales            setCkodeLoket()  Sets the current record's "ckode_loket" value
 * @method TblSales            setCnama()       Sets the current record's "cnama" value
 * @method TblSales            setCtransfer()   Sets the current record's "ctransfer" value
 * @method TblSales            setCalamat()     Sets the current record's "calamat" value
 * @method TblSales            setCstatus()     Sets the current record's "cstatus" value
 * @method TblSales            setTblLoket()    Sets the current record's "TblLoket" value
 * @method TblSales            setTblCustomer() Sets the current record's "TblCustomer" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblSales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_sales');
        $this->hasColumn('ckode_sales', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 9,
             ));
        $this->hasColumn('ckode_loket', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('cnama', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('ctransfer', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'N',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('calamat', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('cstatus', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'A',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TblLoket', array(
             'local' => 'ckode_loket',
             'foreign' => 'ckode_loket'));

        $this->hasMany('TblCustomer', array(
             'local' => 'ckode_sales',
             'foreign' => 'ckode_sales'));
    }
}