<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblLoket', 'doctrine');

/**
 * BaseTblLoket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ckode_loket
 * @property string $cketerangan
 * @property string $delivery_address
 * @property string $phone
 * @property string $phone2
 * @property string $fax
 * @property string $email
 * @property string $contact
 * @property integer $inactive
 * @property Doctrine_Collection $TblCustomer
 * @property Doctrine_Collection $TblSales
 * 
 * @method string              getCkodeLoket()       Returns the current record's "ckode_loket" value
 * @method string              getCketerangan()      Returns the current record's "cketerangan" value
 * @method string              getDeliveryAddress()  Returns the current record's "delivery_address" value
 * @method string              getPhone()            Returns the current record's "phone" value
 * @method string              getPhone2()           Returns the current record's "phone2" value
 * @method string              getFax()              Returns the current record's "fax" value
 * @method string              getEmail()            Returns the current record's "email" value
 * @method string              getContact()          Returns the current record's "contact" value
 * @method integer             getInactive()         Returns the current record's "inactive" value
 * @method Doctrine_Collection getTblCustomer()      Returns the current record's "TblCustomer" collection
 * @method Doctrine_Collection getTblSales()         Returns the current record's "TblSales" collection
 * @method TblLoket            setCkodeLoket()       Sets the current record's "ckode_loket" value
 * @method TblLoket            setCketerangan()      Sets the current record's "cketerangan" value
 * @method TblLoket            setDeliveryAddress()  Sets the current record's "delivery_address" value
 * @method TblLoket            setPhone()            Sets the current record's "phone" value
 * @method TblLoket            setPhone2()           Sets the current record's "phone2" value
 * @method TblLoket            setFax()              Sets the current record's "fax" value
 * @method TblLoket            setEmail()            Sets the current record's "email" value
 * @method TblLoket            setContact()          Sets the current record's "contact" value
 * @method TblLoket            setInactive()         Sets the current record's "inactive" value
 * @method TblLoket            setTblCustomer()      Sets the current record's "TblCustomer" collection
 * @method TblLoket            setTblSales()         Sets the current record's "TblSales" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblLoket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_loket');
        $this->hasColumn('ckode_loket', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('cketerangan', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('delivery_address', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('phone2', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('fax', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('contact', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('inactive', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblCustomer', array(
             'local' => 'ckode_loket',
             'foreign' => 'ckode_loket'));

        $this->hasMany('TblSales', array(
             'local' => 'ckode_loket',
             'foreign' => 'ckode_loket'));
    }
}