<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblJenisbayar', 'doctrine');

/**
 * BaseTblJenisbayar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ckode_jenisbayar
 * @property string $cketerangan
 * @property Doctrine_Collection $TblCustomer
 * 
 * @method string              getCkodeJenisbayar()  Returns the current record's "ckode_jenisbayar" value
 * @method string              getCketerangan()      Returns the current record's "cketerangan" value
 * @method Doctrine_Collection getTblCustomer()      Returns the current record's "TblCustomer" collection
 * @method TblJenisbayar       setCkodeJenisbayar()  Sets the current record's "ckode_jenisbayar" value
 * @method TblJenisbayar       setCketerangan()      Sets the current record's "cketerangan" value
 * @method TblJenisbayar       setTblCustomer()      Sets the current record's "TblCustomer" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblJenisbayar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_jenisbayar');
        $this->hasColumn('ckode_jenisbayar', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('cketerangan', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblCustomer', array(
             'local' => 'ckode_jenisbayar',
             'foreign' => 'cpayment'));
    }
}