<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EdupediaLocation', 'doctrine');

/**
 * BaseEdupediaLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $root_id
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $TblCustomer
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getRootId()      Returns the current record's "root_id" value
 * @method integer             getLft()         Returns the current record's "lft" value
 * @method integer             getRgt()         Returns the current record's "rgt" value
 * @method integer             getLevel()       Returns the current record's "level" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getTblCustomer() Returns the current record's "TblCustomer" collection
 * @method EdupediaLocation    setId()          Sets the current record's "id" value
 * @method EdupediaLocation    setName()        Sets the current record's "name" value
 * @method EdupediaLocation    setRootId()      Sets the current record's "root_id" value
 * @method EdupediaLocation    setLft()         Sets the current record's "lft" value
 * @method EdupediaLocation    setRgt()         Sets the current record's "rgt" value
 * @method EdupediaLocation    setLevel()       Sets the current record's "level" value
 * @method EdupediaLocation    setCreatedAt()   Sets the current record's "created_at" value
 * @method EdupediaLocation    setUpdatedAt()   Sets the current record's "updated_at" value
 * @method EdupediaLocation    setTblCustomer() Sets the current record's "TblCustomer" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEdupediaLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('edupedia_location');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('root_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('lft', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rgt', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('level', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblCustomer', array(
             'local' => 'id',
             'foreign' => 'lokasi_id'));
    }
}