<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblStatuscust', 'doctrine');

/**
 * BaseTblStatuscust
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ckode_statuscust
 * @property string $cketerangan
 * @property Doctrine_Collection $TblCustomer
 * 
 * @method string              getCkodeStatuscust()  Returns the current record's "ckode_statuscust" value
 * @method string              getCketerangan()      Returns the current record's "cketerangan" value
 * @method Doctrine_Collection getTblCustomer()      Returns the current record's "TblCustomer" collection
 * @method TblStatuscust       setCkodeStatuscust()  Sets the current record's "ckode_statuscust" value
 * @method TblStatuscust       setCketerangan()      Sets the current record's "cketerangan" value
 * @method TblStatuscust       setTblCustomer()      Sets the current record's "TblCustomer" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblStatuscust extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_statuscust');
        $this->hasColumn('ckode_statuscust', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('cketerangan', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblCustomer', array(
             'local' => 'ckode_statuscust',
             'foreign' => 'cstatus'));
    }
}