<?php

/**
 * CustomerGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lib
 * @subpackage model
 * @author     Wildan Maulana, OpenThink Labs
 */
class CustomerGroup extends BaseCustomerGroup
{
}
