<?php

/**
 * TblBidangusahaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblBidangusahaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblBidangusahaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblBidangusaha');
    }
}