<?php

/**
 * TblLoketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblLoketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblLoketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblLoket');
    }
}