<?php

/**
 * TblSalesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblSalesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblSalesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblSales');
    }
}