<?php

/**
 * TblWilayahTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblWilayahTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblWilayahTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblWilayah');
    }
}