<?php

/**
 * CgroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CgroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CgroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cgroup');
    }
}