<?php

/**
 * EdupediaLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EdupediaLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EdupediaLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EdupediaLocation');
    }
}