<?php

/**
 * TblBidangusaha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lib
 * @subpackage model
 * @author     Wildan Maulana, OpenThink Labs
 */
class TblBidangusaha extends BaseTblBidangusaha
{
}
