<?php

/**
 * TblCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblCustomerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblCustomer');
    }
}