<?php

/**
 * TblJenisbayarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblJenisbayarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblJenisbayarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblJenisbayar');
    }
}