<?php

/**
 * TblJenisbayar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lib
 * @subpackage model
 * @author     Wildan Maulana, OpenThink Labs
 */
class TblJenisbayar extends BaseTblJenisbayar
{
}
