<?php

/**
 * TblStatuscustTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TblStatuscustTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TblStatuscustTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TblStatuscust');
    }
}