<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TblWilayah', 'doctrine');

/**
 * BaseTblWilayah
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ckodepos
 * @property string $cketerangan
 * @property float $latitude
 * @property float $longitude
 * @property string $ctransfer
 * @property Doctrine_Collection $TblCustomer
 * 
 * @method string              getCkodepos()    Returns the current record's "ckodepos" value
 * @method string              getCketerangan() Returns the current record's "cketerangan" value
 * @method float               getLatitude()    Returns the current record's "latitude" value
 * @method float               getLongitude()   Returns the current record's "longitude" value
 * @method string              getCtransfer()   Returns the current record's "ctransfer" value
 * @method Doctrine_Collection getTblCustomer() Returns the current record's "TblCustomer" collection
 * @method TblWilayah          setCkodepos()    Sets the current record's "ckodepos" value
 * @method TblWilayah          setCketerangan() Sets the current record's "cketerangan" value
 * @method TblWilayah          setLatitude()    Sets the current record's "latitude" value
 * @method TblWilayah          setLongitude()   Sets the current record's "longitude" value
 * @method TblWilayah          setCtransfer()   Sets the current record's "ctransfer" value
 * @method TblWilayah          setTblCustomer() Sets the current record's "TblCustomer" collection
 * 
 * @package    POSLoketPelangi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTblWilayah extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tbl_wilayah');
        $this->hasColumn('ckodepos', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('cketerangan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ctransfer', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'N',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TblCustomer', array(
             'local' => 'ckodepos',
             'foreign' => 'ckode_pos'));
    }
}