<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/21 01:20:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=POSLoketPelangi',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
